source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'exportr'
gem 'slim'
gem 'bourbon'
gem 'jquery-rails'
gem 'paperclip', github: 'thoughtbot/paperclip', ref: '1f3a7467'
gem 'therubyracer'
gem 'turnout'
gem 'devise'
gem 'breadcrumbs_on_rails'
gem 'kaminari'
gem 'redcarpet'
gem 'meta-tags'
gem 'aws-sdk', '~> 1.5.7'
gem 'asset_sync'
gem 'newrelic_rpm'
gem 'dalli'