development:
  adapter: postgresql
  username: tessamulforddotcom
  database: tessamulforddotcom
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  username: tessamulforddotcom
  database: tessamulforddotcom
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: tessamulforddotcom
  database: tessamulforddotcom
  port: 5432
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  username: tessamulforddotcom
  database: tessamulforddotcom
  pool: 5
  timeout: 5000
